### ISSUE TITLE
Question about the drone model

### ISSUE THREAD

**Issue by stephane-caron** [mayataka/pybullet_drone#1]
Thanks for sharing this project!

I'm curious about the  `iris_description` model, does it come from a primary source with its own license, or is it original to this project?

**Comment by mayataka** [comment]
Thank you for pointing out it.
As I cannot find the clear licensing declaration, I replaced the iris model with a drone model that is provided under the MIT license.

**Comment by stephane-caron** [comment]
OK, sorry for the trouble and thanks for pointing out to the Crazyflie model.

I've added it to [awesome-robot-models](https://github.com/tasts-robots/awesome-robot-models/blob/main/README.md#drones). Other robot models are welcome!
